FROM golang:alpine

WORKDIR /app

RUN go install github.com/air-verse/air@v1.61.7 && \
    go install github.com/pressly/goose/v3/cmd/goose@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]
