// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (
    site_id,
    title,
    content,
    priority,
    published_at,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, site_id, title, content, priority, published_at, created_by, created_at, updated_at
`

type CreateAnnouncementParams struct {
	SiteID      pgtype.UUID        `json:"site_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Priority    string             `json:"priority"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcements, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.SiteID,
		arg.Title,
		arg.Content,
		arg.Priority,
		arg.PublishedAt,
		arg.CreatedBy,
	)
	var i Announcements
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Title,
		&i.Content,
		&i.Priority,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM announcements
WHERE id = $1 AND site_id = $2
`

type DeleteAnnouncementParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, arg.ID, arg.SiteID)
	return err
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT
    a.id,
    a.site_id,
    a.title,
    a.content,
    a.priority,
    a.published_at,
    a.created_by,
    a.created_at,
    a.updated_at,
    u.full_name AS author_name
FROM announcements a
JOIN users u ON a.created_by = u.id
WHERE a.id = $1 AND a.site_id = $2
`

type GetAnnouncementByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

type GetAnnouncementByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Priority    string             `json:"priority"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AuthorName  string             `json:"author_name"`
}

func (q *Queries) GetAnnouncementByID(ctx context.Context, arg GetAnnouncementByIDParams) (GetAnnouncementByIDRow, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, arg.ID, arg.SiteID)
	var i GetAnnouncementByIDRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Title,
		&i.Content,
		&i.Priority,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
	)
	return i, err
}

const listAnnouncementsBySite = `-- name: ListAnnouncementsBySite :many
SELECT
    a.id,
    a.site_id,
    a.title,
    a.content,
    a.priority,
    a.published_at,
    a.created_by,
    a.created_at,
    a.updated_at,
    u.full_name AS author_name
FROM announcements a
JOIN users u ON a.created_by = u.id
WHERE a.site_id = $1
ORDER BY a.published_at DESC
`

type ListAnnouncementsBySiteRow struct {
	ID          pgtype.UUID        `json:"id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Priority    string             `json:"priority"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AuthorName  string             `json:"author_name"`
}

func (q *Queries) ListAnnouncementsBySite(ctx context.Context, siteID pgtype.UUID) ([]ListAnnouncementsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementsBySiteRow{}
	for rows.Next() {
		var i ListAnnouncementsBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Title,
			&i.Content,
			&i.Priority,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements
SET
    title = $3,
    content = $4,
    priority = $5,
    updated_at = NOW()
WHERE id = $1 AND site_id = $2
RETURNING id, site_id, title, content, priority, published_at, created_by, created_at, updated_at
`

type UpdateAnnouncementParams struct {
	ID       pgtype.UUID `json:"id"`
	SiteID   pgtype.UUID `json:"site_id"`
	Title    string      `json:"title"`
	Content  string      `json:"content"`
	Priority string      `json:"priority"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcements, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.ID,
		arg.SiteID,
		arg.Title,
		arg.Content,
		arg.Priority,
	)
	var i Announcements
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Title,
		&i.Content,
		&i.Priority,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
