// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apartments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveApartmentsBySiteID = `-- name: CountActiveApartmentsBySiteID :one
SELECT COUNT(*) FROM apartments
WHERE site_id = $1 AND is_active = TRUE
`

func (q *Queries) CountActiveApartmentsBySiteID(ctx context.Context, siteID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveApartmentsBySiteID, siteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApartment = `-- name: CreateApartment :one
INSERT INTO apartments (
    site_id,
    block_id,
    door_number,
    floor,
    owner_user_id,
    tenant_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, site_id, block_id, door_number, floor, owner_user_id, tenant_user_id, is_active, deleted_at, created_at, updated_at
`

type CreateApartmentParams struct {
	SiteID       pgtype.UUID `json:"site_id"`
	BlockID      pgtype.UUID `json:"block_id"`
	DoorNumber   string      `json:"door_number"`
	Floor        pgtype.Int4 `json:"floor"`
	OwnerUserID  pgtype.UUID `json:"owner_user_id"`
	TenantUserID pgtype.UUID `json:"tenant_user_id"`
}

func (q *Queries) CreateApartment(ctx context.Context, arg CreateApartmentParams) (Apartments, error) {
	row := q.db.QueryRow(ctx, createApartment,
		arg.SiteID,
		arg.BlockID,
		arg.DoorNumber,
		arg.Floor,
		arg.OwnerUserID,
		arg.TenantUserID,
	)
	var i Apartments
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.BlockID,
		&i.DoorNumber,
		&i.Floor,
		&i.OwnerUserID,
		&i.TenantUserID,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApartmentByID = `-- name: GetApartmentByID :one
SELECT 
    a.id,
    a.site_id,
    a.block_id,
    b.name AS block_name,
    a.door_number,
    a.floor,
    a.owner_user_id,
    u_owner.full_name AS owner_full_name,
    u_owner.phone AS owner_phone,
    u_owner.email AS owner_email,
    a.tenant_user_id,
    u_tenant.full_name AS tenant_full_name,
    u_tenant.phone AS tenant_phone,
    u_tenant.email AS tenant_email,
    a.is_active,
    a.created_at,
    a.updated_at
FROM apartments a
LEFT JOIN blocks b ON b.id = a.block_id
LEFT JOIN users u_owner ON u_owner.id = a.owner_user_id
LEFT JOIN users u_tenant ON u_tenant.id = a.tenant_user_id
WHERE a.id = $1 AND a.site_id = $2
LIMIT 1
`

type GetApartmentByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

type GetApartmentByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	SiteID         pgtype.UUID        `json:"site_id"`
	BlockID        pgtype.UUID        `json:"block_id"`
	BlockName      pgtype.Text        `json:"block_name"`
	DoorNumber     string             `json:"door_number"`
	Floor          pgtype.Int4        `json:"floor"`
	OwnerUserID    pgtype.UUID        `json:"owner_user_id"`
	OwnerFullName  pgtype.Text        `json:"owner_full_name"`
	OwnerPhone     pgtype.Text        `json:"owner_phone"`
	OwnerEmail     pgtype.Text        `json:"owner_email"`
	TenantUserID   pgtype.UUID        `json:"tenant_user_id"`
	TenantFullName pgtype.Text        `json:"tenant_full_name"`
	TenantPhone    pgtype.Text        `json:"tenant_phone"`
	TenantEmail    pgtype.Text        `json:"tenant_email"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetApartmentByID(ctx context.Context, arg GetApartmentByIDParams) (GetApartmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getApartmentByID, arg.ID, arg.SiteID)
	var i GetApartmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.BlockID,
		&i.BlockName,
		&i.DoorNumber,
		&i.Floor,
		&i.OwnerUserID,
		&i.OwnerFullName,
		&i.OwnerPhone,
		&i.OwnerEmail,
		&i.TenantUserID,
		&i.TenantFullName,
		&i.TenantPhone,
		&i.TenantEmail,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApartmentsBySiteID = `-- name: ListApartmentsBySiteID :many
SELECT 
    a.id,
    a.site_id,
    a.block_id,
    b.name AS block_name,
    a.door_number,
    a.floor,
    a.owner_user_id,
    u_owner.full_name AS owner_full_name,
    u_owner.phone AS owner_phone,
    u_owner.email AS owner_email,
    a.tenant_user_id,
    u_tenant.full_name AS tenant_full_name,
    u_tenant.phone AS tenant_phone,
    u_tenant.email AS tenant_email,
    a.is_active,
    a.created_at,
    a.updated_at
FROM apartments a
LEFT JOIN blocks b ON b.id = a.block_id
LEFT JOIN users u_owner ON u_owner.id = a.owner_user_id
LEFT JOIN users u_tenant ON u_tenant.id = a.tenant_user_id
WHERE a.site_id = $1 AND a.is_active = TRUE
ORDER BY b.name ASC NULLS FIRST, a.door_number ASC
`

type ListApartmentsBySiteIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	SiteID         pgtype.UUID        `json:"site_id"`
	BlockID        pgtype.UUID        `json:"block_id"`
	BlockName      pgtype.Text        `json:"block_name"`
	DoorNumber     string             `json:"door_number"`
	Floor          pgtype.Int4        `json:"floor"`
	OwnerUserID    pgtype.UUID        `json:"owner_user_id"`
	OwnerFullName  pgtype.Text        `json:"owner_full_name"`
	OwnerPhone     pgtype.Text        `json:"owner_phone"`
	OwnerEmail     pgtype.Text        `json:"owner_email"`
	TenantUserID   pgtype.UUID        `json:"tenant_user_id"`
	TenantFullName pgtype.Text        `json:"tenant_full_name"`
	TenantPhone    pgtype.Text        `json:"tenant_phone"`
	TenantEmail    pgtype.Text        `json:"tenant_email"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListApartmentsBySiteID(ctx context.Context, siteID pgtype.UUID) ([]ListApartmentsBySiteIDRow, error) {
	rows, err := q.db.Query(ctx, listApartmentsBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApartmentsBySiteIDRow{}
	for rows.Next() {
		var i ListApartmentsBySiteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.BlockID,
			&i.BlockName,
			&i.DoorNumber,
			&i.Floor,
			&i.OwnerUserID,
			&i.OwnerFullName,
			&i.OwnerPhone,
			&i.OwnerEmail,
			&i.TenantUserID,
			&i.TenantFullName,
			&i.TenantPhone,
			&i.TenantEmail,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeApartmentTenant = `-- name: RemoveApartmentTenant :exec
UPDATE apartments
SET tenant_user_id = NULL, updated_at = NOW()
WHERE id = $1 AND site_id = $2
`

type RemoveApartmentTenantParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) RemoveApartmentTenant(ctx context.Context, arg RemoveApartmentTenantParams) error {
	_, err := q.db.Exec(ctx, removeApartmentTenant, arg.ID, arg.SiteID)
	return err
}

const setApartmentOwner = `-- name: SetApartmentOwner :exec
UPDATE apartments
SET owner_user_id = $3, updated_at = NOW()
WHERE id = $1 AND site_id = $2
`

type SetApartmentOwnerParams struct {
	ID          pgtype.UUID `json:"id"`
	SiteID      pgtype.UUID `json:"site_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) SetApartmentOwner(ctx context.Context, arg SetApartmentOwnerParams) error {
	_, err := q.db.Exec(ctx, setApartmentOwner, arg.ID, arg.SiteID, arg.OwnerUserID)
	return err
}

const setApartmentTenant = `-- name: SetApartmentTenant :exec
UPDATE apartments
SET tenant_user_id = $3, updated_at = NOW()
WHERE id = $1 AND site_id = $2
`

type SetApartmentTenantParams struct {
	ID           pgtype.UUID `json:"id"`
	SiteID       pgtype.UUID `json:"site_id"`
	TenantUserID pgtype.UUID `json:"tenant_user_id"`
}

func (q *Queries) SetApartmentTenant(ctx context.Context, arg SetApartmentTenantParams) error {
	_, err := q.db.Exec(ctx, setApartmentTenant, arg.ID, arg.SiteID, arg.TenantUserID)
	return err
}

const softDeleteApartment = `-- name: SoftDeleteApartment :exec
UPDATE apartments
SET is_active = FALSE, deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND site_id = $2
`

type SoftDeleteApartmentParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) SoftDeleteApartment(ctx context.Context, arg SoftDeleteApartmentParams) error {
	_, err := q.db.Exec(ctx, softDeleteApartment, arg.ID, arg.SiteID)
	return err
}

const updateApartment = `-- name: UpdateApartment :one
UPDATE apartments
SET block_id = $3, door_number = $4, floor = $5, updated_at = NOW()
WHERE id = $1 AND site_id = $2
RETURNING id, site_id, block_id, door_number, floor, owner_user_id, tenant_user_id, is_active, deleted_at, created_at, updated_at
`

type UpdateApartmentParams struct {
	ID         pgtype.UUID `json:"id"`
	SiteID     pgtype.UUID `json:"site_id"`
	BlockID    pgtype.UUID `json:"block_id"`
	DoorNumber string      `json:"door_number"`
	Floor      pgtype.Int4 `json:"floor"`
}

func (q *Queries) UpdateApartment(ctx context.Context, arg UpdateApartmentParams) (Apartments, error) {
	row := q.db.QueryRow(ctx, updateApartment,
		arg.ID,
		arg.SiteID,
		arg.BlockID,
		arg.DoorNumber,
		arg.Floor,
	)
	var i Apartments
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.BlockID,
		&i.DoorNumber,
		&i.Floor,
		&i.OwnerUserID,
		&i.TenantUserID,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
