// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlock = `-- name: CreateBlock :one
INSERT INTO blocks (site_id, name)
VALUES ($1, $2)
RETURNING id, site_id, name, created_at
`

type CreateBlockParams struct {
	SiteID pgtype.UUID `json:"site_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (Blocks, error) {
	row := q.db.QueryRow(ctx, createBlock, arg.SiteID, arg.Name)
	var i Blocks
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks
WHERE id = $1 AND site_id = $2
`

type DeleteBlockParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.ID, arg.SiteID)
	return err
}

const listBlocksBySiteID = `-- name: ListBlocksBySiteID :many
SELECT id, site_id, name, created_at FROM blocks
WHERE site_id = $1
ORDER BY name ASC
`

func (q *Queries) ListBlocksBySiteID(ctx context.Context, siteID pgtype.UUID) ([]Blocks, error) {
	rows, err := q.db.Query(ctx, listBlocksBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blocks{}
	for rows.Next() {
		var i Blocks
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
