// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consumption_periods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConsumptionPeriod = `-- name: CreateConsumptionPeriod :one
INSERT INTO consumption_periods (
    site_id,
    meter_type_id,
    period,
    main_meter_previous,
    main_meter_current,
    total_billed_consumption,
    total_apartments_consumption,
    common_area_consumption,
    total_bill_amount,
    unit_cost,
    common_area_cost,
    bill_date,
    bill_no,
    description,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, site_id, meter_type_id, period, main_meter_previous, main_meter_current, total_billed_consumption, total_apartments_consumption, common_area_consumption, total_bill_amount, unit_cost, common_area_cost, bill_date, bill_no, description, created_by, created_at, updated_at
`

type CreateConsumptionPeriodParams struct {
	SiteID                     pgtype.UUID    `json:"site_id"`
	MeterTypeID                pgtype.UUID    `json:"meter_type_id"`
	Period                     pgtype.Date    `json:"period"`
	MainMeterPrevious          pgtype.Numeric `json:"main_meter_previous"`
	MainMeterCurrent           pgtype.Numeric `json:"main_meter_current"`
	TotalBilledConsumption     pgtype.Numeric `json:"total_billed_consumption"`
	TotalApartmentsConsumption pgtype.Numeric `json:"total_apartments_consumption"`
	CommonAreaConsumption      pgtype.Numeric `json:"common_area_consumption"`
	TotalBillAmount            pgtype.Numeric `json:"total_bill_amount"`
	UnitCost                   pgtype.Numeric `json:"unit_cost"`
	CommonAreaCost             pgtype.Numeric `json:"common_area_cost"`
	BillDate                   pgtype.Date    `json:"bill_date"`
	BillNo                     pgtype.Text    `json:"bill_no"`
	Description                pgtype.Text    `json:"description"`
	CreatedBy                  pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateConsumptionPeriod(ctx context.Context, arg CreateConsumptionPeriodParams) (ConsumptionPeriods, error) {
	row := q.db.QueryRow(ctx, createConsumptionPeriod,
		arg.SiteID,
		arg.MeterTypeID,
		arg.Period,
		arg.MainMeterPrevious,
		arg.MainMeterCurrent,
		arg.TotalBilledConsumption,
		arg.TotalApartmentsConsumption,
		arg.CommonAreaConsumption,
		arg.TotalBillAmount,
		arg.UnitCost,
		arg.CommonAreaCost,
		arg.BillDate,
		arg.BillNo,
		arg.Description,
		arg.CreatedBy,
	)
	var i ConsumptionPeriods
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.MeterTypeID,
		&i.Period,
		&i.MainMeterPrevious,
		&i.MainMeterCurrent,
		&i.TotalBilledConsumption,
		&i.TotalApartmentsConsumption,
		&i.CommonAreaConsumption,
		&i.TotalBillAmount,
		&i.UnitCost,
		&i.CommonAreaCost,
		&i.BillDate,
		&i.BillNo,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMeterReading = `-- name: CreateMeterReading :one
INSERT INTO meter_readings (
    consumption_period_id,
    apartment_id,
    previous_reading,
    current_reading,
    consumption,
    individual_amount,
    common_area_amount,
    total_amount,
    debt_id,
    debtor_user_id,
    reading_date,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, consumption_period_id, apartment_id, previous_reading, current_reading, consumption, individual_amount, common_area_amount, total_amount, debt_id, debtor_user_id, reading_date, notes, created_at
`

type CreateMeterReadingParams struct {
	ConsumptionPeriodID pgtype.UUID    `json:"consumption_period_id"`
	ApartmentID         pgtype.UUID    `json:"apartment_id"`
	PreviousReading     pgtype.Numeric `json:"previous_reading"`
	CurrentReading      pgtype.Numeric `json:"current_reading"`
	Consumption         pgtype.Numeric `json:"consumption"`
	IndividualAmount    pgtype.Numeric `json:"individual_amount"`
	CommonAreaAmount    pgtype.Numeric `json:"common_area_amount"`
	TotalAmount         pgtype.Numeric `json:"total_amount"`
	DebtID              pgtype.UUID    `json:"debt_id"`
	DebtorUserID        pgtype.UUID    `json:"debtor_user_id"`
	ReadingDate         pgtype.Date    `json:"reading_date"`
	Notes               pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateMeterReading(ctx context.Context, arg CreateMeterReadingParams) (MeterReadings, error) {
	row := q.db.QueryRow(ctx, createMeterReading,
		arg.ConsumptionPeriodID,
		arg.ApartmentID,
		arg.PreviousReading,
		arg.CurrentReading,
		arg.Consumption,
		arg.IndividualAmount,
		arg.CommonAreaAmount,
		arg.TotalAmount,
		arg.DebtID,
		arg.DebtorUserID,
		arg.ReadingDate,
		arg.Notes,
	)
	var i MeterReadings
	err := row.Scan(
		&i.ID,
		&i.ConsumptionPeriodID,
		&i.ApartmentID,
		&i.PreviousReading,
		&i.CurrentReading,
		&i.Consumption,
		&i.IndividualAmount,
		&i.CommonAreaAmount,
		&i.TotalAmount,
		&i.DebtID,
		&i.DebtorUserID,
		&i.ReadingDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConsumptionPeriod = `-- name: DeleteConsumptionPeriod :exec
DELETE FROM consumption_periods
WHERE id = $1 AND site_id = $2
`

type DeleteConsumptionPeriodParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) DeleteConsumptionPeriod(ctx context.Context, arg DeleteConsumptionPeriodParams) error {
	_, err := q.db.Exec(ctx, deleteConsumptionPeriod, arg.ID, arg.SiteID)
	return err
}

const getConsumptionPeriodByID = `-- name: GetConsumptionPeriodByID :one
SELECT
    cp.id, cp.site_id, cp.meter_type_id, cp.period, cp.main_meter_previous, cp.main_meter_current, cp.total_billed_consumption, cp.total_apartments_consumption, cp.common_area_consumption, cp.total_bill_amount, cp.unit_cost, cp.common_area_cost, cp.bill_date, cp.bill_no, cp.description, cp.created_by, cp.created_at, cp.updated_at,
    mt.name AS meter_type_name,
    mt.unit AS meter_type_unit
FROM consumption_periods cp
JOIN meter_types mt ON cp.meter_type_id = mt.id
WHERE cp.id = $1 AND cp.site_id = $2
LIMIT 1
`

type GetConsumptionPeriodByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

type GetConsumptionPeriodByIDRow struct {
	ID                         pgtype.UUID        `json:"id"`
	SiteID                     pgtype.UUID        `json:"site_id"`
	MeterTypeID                pgtype.UUID        `json:"meter_type_id"`
	Period                     pgtype.Date        `json:"period"`
	MainMeterPrevious          pgtype.Numeric     `json:"main_meter_previous"`
	MainMeterCurrent           pgtype.Numeric     `json:"main_meter_current"`
	TotalBilledConsumption     pgtype.Numeric     `json:"total_billed_consumption"`
	TotalApartmentsConsumption pgtype.Numeric     `json:"total_apartments_consumption"`
	CommonAreaConsumption      pgtype.Numeric     `json:"common_area_consumption"`
	TotalBillAmount            pgtype.Numeric     `json:"total_bill_amount"`
	UnitCost                   pgtype.Numeric     `json:"unit_cost"`
	CommonAreaCost             pgtype.Numeric     `json:"common_area_cost"`
	BillDate                   pgtype.Date        `json:"bill_date"`
	BillNo                     pgtype.Text        `json:"bill_no"`
	Description                pgtype.Text        `json:"description"`
	CreatedBy                  pgtype.UUID        `json:"created_by"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	MeterTypeName              string             `json:"meter_type_name"`
	MeterTypeUnit              string             `json:"meter_type_unit"`
}

func (q *Queries) GetConsumptionPeriodByID(ctx context.Context, arg GetConsumptionPeriodByIDParams) (GetConsumptionPeriodByIDRow, error) {
	row := q.db.QueryRow(ctx, getConsumptionPeriodByID, arg.ID, arg.SiteID)
	var i GetConsumptionPeriodByIDRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.MeterTypeID,
		&i.Period,
		&i.MainMeterPrevious,
		&i.MainMeterCurrent,
		&i.TotalBilledConsumption,
		&i.TotalApartmentsConsumption,
		&i.CommonAreaConsumption,
		&i.TotalBillAmount,
		&i.UnitCost,
		&i.CommonAreaCost,
		&i.BillDate,
		&i.BillNo,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MeterTypeName,
		&i.MeterTypeUnit,
	)
	return i, err
}

const getDebtIDsByPeriodID = `-- name: GetDebtIDsByPeriodID :many
SELECT debt_id FROM meter_readings
WHERE consumption_period_id = $1 AND debt_id IS NOT NULL
`

func (q *Queries) GetDebtIDsByPeriodID(ctx context.Context, consumptionPeriodID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getDebtIDsByPeriodID, consumptionPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var debt_id pgtype.UUID
		if err := rows.Scan(&debt_id); err != nil {
			return nil, err
		}
		items = append(items, debt_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastApartmentReadings = `-- name: GetLastApartmentReadings :many
WITH latest_period AS (
    SELECT id
    FROM consumption_periods
    WHERE site_id = $1 AND meter_type_id = $2
    ORDER BY period DESC, created_at DESC
    LIMIT 1
),
unpaid_utility_debts AS (
    SELECT 
        ds.apartment_id,
        COALESCE(SUM(ds.remaining), 0)::NUMERIC(10, 2) AS previous_debt
    FROM debt_summary ds
    JOIN meter_types mt ON mt.id = $2
    WHERE ds.site_id = $1 
      AND ds.type = 'utility' 
      AND ds.status != 'paid'
      AND (ds.description ILIKE '%' || mt.name || '%' OR ds.description IS NULL)
    GROUP BY ds.apartment_id
)
SELECT
    a.id AS apartment_id,
    a.door_number,
    b.name AS block_name,
    COALESCE(r.current_reading, 0)::NUMERIC(12, 3) AS last_reading,
    COALESCE(uud.previous_debt, 0)::NUMERIC(10, 2) AS previous_debt
FROM apartments a
LEFT JOIN blocks b ON a.block_id = b.id
LEFT JOIN latest_period lp ON TRUE
LEFT JOIN meter_readings r ON r.consumption_period_id = lp.id AND r.apartment_id = a.id
LEFT JOIN unpaid_utility_debts uud ON uud.apartment_id = a.id
WHERE a.site_id = $1 AND a.is_active = TRUE
ORDER BY b.name NULLS FIRST, a.door_number ASC
`

type GetLastApartmentReadingsParams struct {
	SiteID      pgtype.UUID `json:"site_id"`
	MeterTypeID pgtype.UUID `json:"meter_type_id"`
}

type GetLastApartmentReadingsRow struct {
	ApartmentID  pgtype.UUID    `json:"apartment_id"`
	DoorNumber   string         `json:"door_number"`
	BlockName    pgtype.Text    `json:"block_name"`
	LastReading  pgtype.Numeric `json:"last_reading"`
	PreviousDebt pgtype.Numeric `json:"previous_debt"`
}

func (q *Queries) GetLastApartmentReadings(ctx context.Context, arg GetLastApartmentReadingsParams) ([]GetLastApartmentReadingsRow, error) {
	rows, err := q.db.Query(ctx, getLastApartmentReadings, arg.SiteID, arg.MeterTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLastApartmentReadingsRow{}
	for rows.Next() {
		var i GetLastApartmentReadingsRow
		if err := rows.Scan(
			&i.ApartmentID,
			&i.DoorNumber,
			&i.BlockName,
			&i.LastReading,
			&i.PreviousDebt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastMainMeterReading = `-- name: GetLastMainMeterReading :one
SELECT COALESCE(main_meter_current, 0)::NUMERIC(12, 3) AS last_reading
FROM consumption_periods
WHERE site_id = $1 AND meter_type_id = $2
ORDER BY period DESC, created_at DESC
LIMIT 1
`

type GetLastMainMeterReadingParams struct {
	SiteID      pgtype.UUID `json:"site_id"`
	MeterTypeID pgtype.UUID `json:"meter_type_id"`
}

func (q *Queries) GetLastMainMeterReading(ctx context.Context, arg GetLastMainMeterReadingParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getLastMainMeterReading, arg.SiteID, arg.MeterTypeID)
	var last_reading pgtype.Numeric
	err := row.Scan(&last_reading)
	return last_reading, err
}

const getResidentMeterHistoryByApartmentID = `-- name: GetResidentMeterHistoryByApartmentID :many
SELECT
    mr.id AS reading_id,
    mr.reading_date,
    mr.previous_reading,
    mr.current_reading,
    mr.consumption,
    mr.individual_amount,
    mr.common_area_amount,
    mr.total_amount,
    d.id AS debt_id,
    d.status AS debt_status,
    cp.period,
    cp.bill_date,
    cp.bill_no,
    cp.total_bill_amount,
    cp.unit_cost,
    cp.total_billed_consumption,
    cp.common_area_consumption,
    mt.name AS meter_type_name,
    mt.unit AS meter_type_unit
FROM meter_readings mr
JOIN consumption_periods cp ON mr.consumption_period_id = cp.id
JOIN meter_types mt ON cp.meter_type_id = mt.id
LEFT JOIN debts d ON mr.debt_id = d.id
WHERE mr.apartment_id = $1
ORDER BY cp.period DESC, mr.created_at DESC
`

type GetResidentMeterHistoryByApartmentIDRow struct {
	ReadingID              pgtype.UUID    `json:"reading_id"`
	ReadingDate            pgtype.Date    `json:"reading_date"`
	PreviousReading        pgtype.Numeric `json:"previous_reading"`
	CurrentReading         pgtype.Numeric `json:"current_reading"`
	Consumption            pgtype.Numeric `json:"consumption"`
	IndividualAmount       pgtype.Numeric `json:"individual_amount"`
	CommonAreaAmount       pgtype.Numeric `json:"common_area_amount"`
	TotalAmount            pgtype.Numeric `json:"total_amount"`
	DebtID                 pgtype.UUID    `json:"debt_id"`
	DebtStatus             pgtype.Text    `json:"debt_status"`
	Period                 pgtype.Date    `json:"period"`
	BillDate               pgtype.Date    `json:"bill_date"`
	BillNo                 pgtype.Text    `json:"bill_no"`
	TotalBillAmount        pgtype.Numeric `json:"total_bill_amount"`
	UnitCost               pgtype.Numeric `json:"unit_cost"`
	TotalBilledConsumption pgtype.Numeric `json:"total_billed_consumption"`
	CommonAreaConsumption  pgtype.Numeric `json:"common_area_consumption"`
	MeterTypeName          string         `json:"meter_type_name"`
	MeterTypeUnit          string         `json:"meter_type_unit"`
}

func (q *Queries) GetResidentMeterHistoryByApartmentID(ctx context.Context, apartmentID pgtype.UUID) ([]GetResidentMeterHistoryByApartmentIDRow, error) {
	rows, err := q.db.Query(ctx, getResidentMeterHistoryByApartmentID, apartmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetResidentMeterHistoryByApartmentIDRow{}
	for rows.Next() {
		var i GetResidentMeterHistoryByApartmentIDRow
		if err := rows.Scan(
			&i.ReadingID,
			&i.ReadingDate,
			&i.PreviousReading,
			&i.CurrentReading,
			&i.Consumption,
			&i.IndividualAmount,
			&i.CommonAreaAmount,
			&i.TotalAmount,
			&i.DebtID,
			&i.DebtStatus,
			&i.Period,
			&i.BillDate,
			&i.BillNo,
			&i.TotalBillAmount,
			&i.UnitCost,
			&i.TotalBilledConsumption,
			&i.CommonAreaConsumption,
			&i.MeterTypeName,
			&i.MeterTypeUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsumptionPeriodsBySite = `-- name: ListConsumptionPeriodsBySite :many
SELECT
    cp.id, cp.site_id, cp.meter_type_id, cp.period, cp.main_meter_previous, cp.main_meter_current, cp.total_billed_consumption, cp.total_apartments_consumption, cp.common_area_consumption, cp.total_bill_amount, cp.unit_cost, cp.common_area_cost, cp.bill_date, cp.bill_no, cp.description, cp.created_by, cp.created_at, cp.updated_at,
    mt.name AS meter_type_name,
    mt.unit AS meter_type_unit,
    COUNT(mr.id)::BIGINT AS reading_count
FROM consumption_periods cp
JOIN meter_types mt ON cp.meter_type_id = mt.id
LEFT JOIN meter_readings mr ON mr.consumption_period_id = cp.id
WHERE cp.site_id = $1
GROUP BY cp.id, mt.name, mt.unit
ORDER BY cp.period DESC, cp.created_at DESC
`

type ListConsumptionPeriodsBySiteRow struct {
	ID                         pgtype.UUID        `json:"id"`
	SiteID                     pgtype.UUID        `json:"site_id"`
	MeterTypeID                pgtype.UUID        `json:"meter_type_id"`
	Period                     pgtype.Date        `json:"period"`
	MainMeterPrevious          pgtype.Numeric     `json:"main_meter_previous"`
	MainMeterCurrent           pgtype.Numeric     `json:"main_meter_current"`
	TotalBilledConsumption     pgtype.Numeric     `json:"total_billed_consumption"`
	TotalApartmentsConsumption pgtype.Numeric     `json:"total_apartments_consumption"`
	CommonAreaConsumption      pgtype.Numeric     `json:"common_area_consumption"`
	TotalBillAmount            pgtype.Numeric     `json:"total_bill_amount"`
	UnitCost                   pgtype.Numeric     `json:"unit_cost"`
	CommonAreaCost             pgtype.Numeric     `json:"common_area_cost"`
	BillDate                   pgtype.Date        `json:"bill_date"`
	BillNo                     pgtype.Text        `json:"bill_no"`
	Description                pgtype.Text        `json:"description"`
	CreatedBy                  pgtype.UUID        `json:"created_by"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	MeterTypeName              string             `json:"meter_type_name"`
	MeterTypeUnit              string             `json:"meter_type_unit"`
	ReadingCount               int64              `json:"reading_count"`
}

func (q *Queries) ListConsumptionPeriodsBySite(ctx context.Context, siteID pgtype.UUID) ([]ListConsumptionPeriodsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listConsumptionPeriodsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConsumptionPeriodsBySiteRow{}
	for rows.Next() {
		var i ListConsumptionPeriodsBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.MeterTypeID,
			&i.Period,
			&i.MainMeterPrevious,
			&i.MainMeterCurrent,
			&i.TotalBilledConsumption,
			&i.TotalApartmentsConsumption,
			&i.CommonAreaConsumption,
			&i.TotalBillAmount,
			&i.UnitCost,
			&i.CommonAreaCost,
			&i.BillDate,
			&i.BillNo,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MeterTypeName,
			&i.MeterTypeUnit,
			&i.ReadingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeterReadingsByPeriodID = `-- name: ListMeterReadingsByPeriodID :many
SELECT
    mr.id, mr.consumption_period_id, mr.apartment_id, mr.previous_reading, mr.current_reading, mr.consumption, mr.individual_amount, mr.common_area_amount, mr.total_amount, mr.debt_id, mr.debtor_user_id, mr.reading_date, mr.notes, mr.created_at,
    a.door_number,
    b.name AS block_name,
    u.full_name AS debtor_full_name,
    u.phone AS debtor_phone,
    d.status AS debt_status
FROM meter_readings mr
JOIN apartments a ON mr.apartment_id = a.id
LEFT JOIN blocks b ON a.block_id = b.id
LEFT JOIN users u ON mr.debtor_user_id = u.id
LEFT JOIN debts d ON mr.debt_id = d.id
WHERE mr.consumption_period_id = $1
ORDER BY b.name NULLS FIRST, a.door_number ASC
`

type ListMeterReadingsByPeriodIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	ConsumptionPeriodID pgtype.UUID        `json:"consumption_period_id"`
	ApartmentID         pgtype.UUID        `json:"apartment_id"`
	PreviousReading     pgtype.Numeric     `json:"previous_reading"`
	CurrentReading      pgtype.Numeric     `json:"current_reading"`
	Consumption         pgtype.Numeric     `json:"consumption"`
	IndividualAmount    pgtype.Numeric     `json:"individual_amount"`
	CommonAreaAmount    pgtype.Numeric     `json:"common_area_amount"`
	TotalAmount         pgtype.Numeric     `json:"total_amount"`
	DebtID              pgtype.UUID        `json:"debt_id"`
	DebtorUserID        pgtype.UUID        `json:"debtor_user_id"`
	ReadingDate         pgtype.Date        `json:"reading_date"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	DoorNumber          string             `json:"door_number"`
	BlockName           pgtype.Text        `json:"block_name"`
	DebtorFullName      pgtype.Text        `json:"debtor_full_name"`
	DebtorPhone         pgtype.Text        `json:"debtor_phone"`
	DebtStatus          pgtype.Text        `json:"debt_status"`
}

func (q *Queries) ListMeterReadingsByPeriodID(ctx context.Context, consumptionPeriodID pgtype.UUID) ([]ListMeterReadingsByPeriodIDRow, error) {
	rows, err := q.db.Query(ctx, listMeterReadingsByPeriodID, consumptionPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeterReadingsByPeriodIDRow{}
	for rows.Next() {
		var i ListMeterReadingsByPeriodIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsumptionPeriodID,
			&i.ApartmentID,
			&i.PreviousReading,
			&i.CurrentReading,
			&i.Consumption,
			&i.IndividualAmount,
			&i.CommonAreaAmount,
			&i.TotalAmount,
			&i.DebtID,
			&i.DebtorUserID,
			&i.ReadingDate,
			&i.Notes,
			&i.CreatedAt,
			&i.DoorNumber,
			&i.BlockName,
			&i.DebtorFullName,
			&i.DebtorPhone,
			&i.DebtStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
