// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: debts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accrueMonthlyDue = `-- name: AccrueMonthlyDue :one
INSERT INTO debts (
    site_id, apartment_id, debtor_user_id, type, amount, due_month, description, status, created_by
) VALUES (
    $1, $2, $3, 'monthly_due', $4, $5, $6, 'open', $7
)
ON CONFLICT (apartment_id, due_month) WHERE type = 'monthly_due'
DO NOTHING
RETURNING id
`

type AccrueMonthlyDueParams struct {
	SiteID       pgtype.UUID    `json:"site_id"`
	ApartmentID  pgtype.UUID    `json:"apartment_id"`
	DebtorUserID pgtype.UUID    `json:"debtor_user_id"`
	Amount       pgtype.Numeric `json:"amount"`
	DueMonth     pgtype.Date    `json:"due_month"`
	Description  pgtype.Text    `json:"description"`
	CreatedBy    pgtype.UUID    `json:"created_by"`
}

func (q *Queries) AccrueMonthlyDue(ctx context.Context, arg AccrueMonthlyDueParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, accrueMonthlyDue,
		arg.SiteID,
		arg.ApartmentID,
		arg.DebtorUserID,
		arg.Amount,
		arg.DueMonth,
		arg.Description,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (
    site_id, apartment_id, debtor_user_id, type, amount, due_month, description, status, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, site_id, apartment_id, debtor_user_id, type, amount, due_month, description, status, created_by, created_at, updated_at
`

type CreateDebtParams struct {
	SiteID       pgtype.UUID    `json:"site_id"`
	ApartmentID  pgtype.UUID    `json:"apartment_id"`
	DebtorUserID pgtype.UUID    `json:"debtor_user_id"`
	Type         string         `json:"type"`
	Amount       pgtype.Numeric `json:"amount"`
	DueMonth     pgtype.Date    `json:"due_month"`
	Description  pgtype.Text    `json:"description"`
	Status       string         `json:"status"`
	CreatedBy    pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debts, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.SiteID,
		arg.ApartmentID,
		arg.DebtorUserID,
		arg.Type,
		arg.Amount,
		arg.DueMonth,
		arg.Description,
		arg.Status,
		arg.CreatedBy,
	)
	var i Debts
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ApartmentID,
		&i.DebtorUserID,
		&i.Type,
		&i.Amount,
		&i.DueMonth,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDebtByID = `-- name: DeleteDebtByID :exec
DELETE FROM debts
WHERE id = $1 AND site_id = $2
`

type DeleteDebtByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) DeleteDebtByID(ctx context.Context, arg DeleteDebtByIDParams) error {
	_, err := q.db.Exec(ctx, deleteDebtByID, arg.ID, arg.SiteID)
	return err
}

const deleteOpenDebtsByDebtor = `-- name: DeleteOpenDebtsByDebtor :exec
DELETE FROM debts
WHERE apartment_id = $1 AND debtor_user_id = $2 AND status != 'paid'
`

type DeleteOpenDebtsByDebtorParams struct {
	ApartmentID  pgtype.UUID `json:"apartment_id"`
	DebtorUserID pgtype.UUID `json:"debtor_user_id"`
}

func (q *Queries) DeleteOpenDebtsByDebtor(ctx context.Context, arg DeleteOpenDebtsByDebtorParams) error {
	_, err := q.db.Exec(ctx, deleteOpenDebtsByDebtor, arg.ApartmentID, arg.DebtorUserID)
	return err
}

const getDebtDetailByID = `-- name: GetDebtDetailByID :one
SELECT 
    ds.id,
    ds.site_id,
    ds.apartment_id,
    ds.debtor_user_id,
    ds.type,
    ds.amount,
    ds.due_month,
    ds.description,
    ds.status,
    ds.created_at,
    ds.paid_amount::NUMERIC(10,2) AS paid_amount,
    ds.remaining::NUMERIC(10,2) AS remaining,
    a.door_number,
    COALESCE(b.name, '') AS block_name,
    u.full_name AS debtor_full_name,
    u.phone AS debtor_phone
FROM debt_summary ds
JOIN apartments a ON a.id = ds.apartment_id
LEFT JOIN blocks b ON b.id = a.block_id
JOIN users u ON u.id = ds.debtor_user_id
WHERE ds.id = $1 AND ds.site_id = $2
`

type GetDebtDetailByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

type GetDebtDetailByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	SiteID         pgtype.UUID        `json:"site_id"`
	ApartmentID    pgtype.UUID        `json:"apartment_id"`
	DebtorUserID   pgtype.UUID        `json:"debtor_user_id"`
	Type           string             `json:"type"`
	Amount         pgtype.Numeric     `json:"amount"`
	DueMonth       pgtype.Date        `json:"due_month"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PaidAmount     pgtype.Numeric     `json:"paid_amount"`
	Remaining      pgtype.Numeric     `json:"remaining"`
	DoorNumber     string             `json:"door_number"`
	BlockName      string             `json:"block_name"`
	DebtorFullName string             `json:"debtor_full_name"`
	DebtorPhone    string             `json:"debtor_phone"`
}

func (q *Queries) GetDebtDetailByID(ctx context.Context, arg GetDebtDetailByIDParams) (GetDebtDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getDebtDetailByID, arg.ID, arg.SiteID)
	var i GetDebtDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.ApartmentID,
		&i.DebtorUserID,
		&i.Type,
		&i.Amount,
		&i.DueMonth,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAmount,
		&i.Remaining,
		&i.DoorNumber,
		&i.BlockName,
		&i.DebtorFullName,
		&i.DebtorPhone,
	)
	return i, err
}

const getDebtsStatsBySite = `-- name: GetDebtsStatsBySite :one
SELECT 
    COALESCE(SUM(amount), 0)::NUMERIC(12,2) AS total_amount,
    COALESCE(SUM(paid_amount), 0)::NUMERIC(12,2) AS total_paid,
    COALESCE(SUM(remaining), 0)::NUMERIC(12,2) AS total_remaining,
    COUNT(*)::INT AS total_count,
    COUNT(*) FILTER (WHERE status = 'open')::INT AS open_count,
    COUNT(*) FILTER (WHERE status = 'partial')::INT AS partial_count,
    COUNT(*) FILTER (WHERE status = 'paid')::INT AS paid_count
FROM debt_summary
WHERE site_id = $1
`

type GetDebtsStatsBySiteRow struct {
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	TotalPaid      pgtype.Numeric `json:"total_paid"`
	TotalRemaining pgtype.Numeric `json:"total_remaining"`
	TotalCount     int32          `json:"total_count"`
	OpenCount      int32          `json:"open_count"`
	PartialCount   int32          `json:"partial_count"`
	PaidCount      int32          `json:"paid_count"`
}

func (q *Queries) GetDebtsStatsBySite(ctx context.Context, siteID pgtype.UUID) (GetDebtsStatsBySiteRow, error) {
	row := q.db.QueryRow(ctx, getDebtsStatsBySite, siteID)
	var i GetDebtsStatsBySiteRow
	err := row.Scan(
		&i.TotalAmount,
		&i.TotalPaid,
		&i.TotalRemaining,
		&i.TotalCount,
		&i.OpenCount,
		&i.PartialCount,
		&i.PaidCount,
	)
	return i, err
}

const listActiveApartmentsForAccrual = `-- name: ListActiveApartmentsForAccrual :many
SELECT 
    a.id, 
    a.site_id, 
    a.owner_user_id, 
    a.tenant_user_id
FROM apartments a
WHERE a.site_id = $1 AND a.is_active = TRUE
`

type ListActiveApartmentsForAccrualRow struct {
	ID           pgtype.UUID `json:"id"`
	SiteID       pgtype.UUID `json:"site_id"`
	OwnerUserID  pgtype.UUID `json:"owner_user_id"`
	TenantUserID pgtype.UUID `json:"tenant_user_id"`
}

func (q *Queries) ListActiveApartmentsForAccrual(ctx context.Context, siteID pgtype.UUID) ([]ListActiveApartmentsForAccrualRow, error) {
	rows, err := q.db.Query(ctx, listActiveApartmentsForAccrual, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveApartmentsForAccrualRow{}
	for rows.Next() {
		var i ListActiveApartmentsForAccrualRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.OwnerUserID,
			&i.TenantUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtsBySite = `-- name: ListDebtsBySite :many
SELECT 
    ds.id,
    ds.site_id,
    ds.apartment_id,
    ds.debtor_user_id,
    ds.type,
    ds.amount,
    ds.due_month,
    ds.description,
    ds.status,
    ds.created_at,
    ds.paid_amount::NUMERIC(10,2) AS paid_amount,
    ds.remaining::NUMERIC(10,2) AS remaining,
    a.door_number,
    COALESCE(b.name, '') AS block_name,
    u.full_name AS debtor_full_name,
    u.phone AS debtor_phone
FROM debt_summary ds
JOIN apartments a ON a.id = ds.apartment_id
LEFT JOIN blocks b ON b.id = a.block_id
JOIN users u ON u.id = ds.debtor_user_id
WHERE ds.site_id = $1
  AND ($2::TEXT IS NULL OR ds.status = $2)
  AND ($3::TEXT IS NULL OR ds.type = $3)
  AND ($4::UUID IS NULL OR ds.apartment_id = $4)
  AND ($5::UUID IS NULL OR ds.debtor_user_id = $5)
ORDER BY ds.created_at DESC
`

type ListDebtsBySiteParams struct {
	SiteID       pgtype.UUID `json:"site_id"`
	Status       pgtype.Text `json:"status"`
	Type         pgtype.Text `json:"type"`
	ApartmentID  pgtype.UUID `json:"apartment_id"`
	DebtorUserID pgtype.UUID `json:"debtor_user_id"`
}

type ListDebtsBySiteRow struct {
	ID             pgtype.UUID        `json:"id"`
	SiteID         pgtype.UUID        `json:"site_id"`
	ApartmentID    pgtype.UUID        `json:"apartment_id"`
	DebtorUserID   pgtype.UUID        `json:"debtor_user_id"`
	Type           string             `json:"type"`
	Amount         pgtype.Numeric     `json:"amount"`
	DueMonth       pgtype.Date        `json:"due_month"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PaidAmount     pgtype.Numeric     `json:"paid_amount"`
	Remaining      pgtype.Numeric     `json:"remaining"`
	DoorNumber     string             `json:"door_number"`
	BlockName      string             `json:"block_name"`
	DebtorFullName string             `json:"debtor_full_name"`
	DebtorPhone    string             `json:"debtor_phone"`
}

func (q *Queries) ListDebtsBySite(ctx context.Context, arg ListDebtsBySiteParams) ([]ListDebtsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listDebtsBySite,
		arg.SiteID,
		arg.Status,
		arg.Type,
		arg.ApartmentID,
		arg.DebtorUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDebtsBySiteRow{}
	for rows.Next() {
		var i ListDebtsBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.ApartmentID,
			&i.DebtorUserID,
			&i.Type,
			&i.Amount,
			&i.DueMonth,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.PaidAmount,
			&i.Remaining,
			&i.DoorNumber,
			&i.BlockName,
			&i.DebtorFullName,
			&i.DebtorPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferOpenDebtsToOwner = `-- name: TransferOpenDebtsToOwner :exec
UPDATE debts
SET debtor_user_id = $3, updated_at = NOW()
WHERE apartment_id = $1 AND debtor_user_id = $2 AND status != 'paid'
`

type TransferOpenDebtsToOwnerParams struct {
	ApartmentID    pgtype.UUID `json:"apartment_id"`
	DebtorUserID   pgtype.UUID `json:"debtor_user_id"`
	DebtorUserID_2 pgtype.UUID `json:"debtor_user_id_2"`
}

func (q *Queries) TransferOpenDebtsToOwner(ctx context.Context, arg TransferOpenDebtsToOwnerParams) error {
	_, err := q.db.Exec(ctx, transferOpenDebtsToOwner, arg.ApartmentID, arg.DebtorUserID, arg.DebtorUserID_2)
	return err
}

const updateDebtStatus = `-- name: UpdateDebtStatus :exec
UPDATE debts
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateDebtStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDebtStatus(ctx context.Context, arg UpdateDebtStatusParams) error {
	_, err := q.db.Exec(ctx, updateDebtStatus, arg.ID, arg.Status)
	return err
}
