// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: due_rates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentDueRate = `-- name: GetCurrentDueRate :one
SELECT 
    dr.id, 
    dr.site_id, 
    dr.amount, 
    dr.valid_from, 
    dr.created_by, 
    dr.created_at
FROM due_rates dr
WHERE dr.site_id = $1 AND dr.valid_from <= $2
ORDER BY dr.valid_from DESC
LIMIT 1
`

type GetCurrentDueRateParams struct {
	SiteID    pgtype.UUID `json:"site_id"`
	ValidFrom pgtype.Date `json:"valid_from"`
}

func (q *Queries) GetCurrentDueRate(ctx context.Context, arg GetCurrentDueRateParams) (DueRates, error) {
	row := q.db.QueryRow(ctx, getCurrentDueRate, arg.SiteID, arg.ValidFrom)
	var i DueRates
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Amount,
		&i.ValidFrom,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDueRateHistory = `-- name: GetDueRateHistory :many
SELECT 
    dr.id, 
    dr.site_id, 
    dr.amount, 
    dr.valid_from, 
    dr.created_by, 
    dr.created_at, 
    COALESCE(u.full_name, '') AS created_by_name
FROM due_rates dr
LEFT JOIN users u ON u.id = dr.created_by
WHERE dr.site_id = $1
ORDER BY dr.valid_from DESC
`

type GetDueRateHistoryRow struct {
	ID            pgtype.UUID        `json:"id"`
	SiteID        pgtype.UUID        `json:"site_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	ValidFrom     pgtype.Date        `json:"valid_from"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedByName string             `json:"created_by_name"`
}

func (q *Queries) GetDueRateHistory(ctx context.Context, siteID pgtype.UUID) ([]GetDueRateHistoryRow, error) {
	rows, err := q.db.Query(ctx, getDueRateHistory, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDueRateHistoryRow{}
	for rows.Next() {
		var i GetDueRateHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Amount,
			&i.ValidFrom,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDueRate = `-- name: UpsertDueRate :one
INSERT INTO due_rates (site_id, amount, valid_from, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (site_id, valid_from)
DO UPDATE SET amount = EXCLUDED.amount
RETURNING id, site_id, amount, valid_from, created_by, created_at
`

type UpsertDueRateParams struct {
	SiteID    pgtype.UUID    `json:"site_id"`
	Amount    pgtype.Numeric `json:"amount"`
	ValidFrom pgtype.Date    `json:"valid_from"`
	CreatedBy pgtype.UUID    `json:"created_by"`
}

func (q *Queries) UpsertDueRate(ctx context.Context, arg UpsertDueRateParams) (DueRates, error) {
	row := q.db.QueryRow(ctx, upsertDueRate,
		arg.SiteID,
		arg.Amount,
		arg.ValidFrom,
		arg.CreatedBy,
	)
	var i DueRates
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Amount,
		&i.ValidFrom,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
