// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    site_id,
    category_id,
    amount,
    description,
    expense_date,
    receipt_note,
    recorded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, site_id, category_id, amount, description, expense_date, receipt_note, recorded_by, created_at, updated_at
`

type CreateExpenseParams struct {
	SiteID      pgtype.UUID    `json:"site_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Description pgtype.Text    `json:"description"`
	ExpenseDate pgtype.Date    `json:"expense_date"`
	ReceiptNote pgtype.Text    `json:"receipt_note"`
	RecordedBy  pgtype.UUID    `json:"recorded_by"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expenses, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.SiteID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.ExpenseDate,
		arg.ReceiptNote,
		arg.RecordedBy,
	)
	var i Expenses
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.ExpenseDate,
		&i.ReceiptNote,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpenseByID = `-- name: DeleteExpenseByID :exec
DELETE FROM expenses
WHERE id = $1 AND site_id = $2
`

type DeleteExpenseByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) DeleteExpenseByID(ctx context.Context, arg DeleteExpenseByIDParams) error {
	_, err := q.db.Exec(ctx, deleteExpenseByID, arg.ID, arg.SiteID)
	return err
}

const getCategoryBreakdownBySite = `-- name: GetCategoryBreakdownBySite :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    COALESCE(SUM(e.amount), 0)::NUMERIC(10,2) AS total_amount,
    COUNT(e.id)::BIGINT AS expense_count
FROM expense_categories c
LEFT JOIN expenses e ON e.category_id = c.id
WHERE c.site_id = $1
GROUP BY c.id, c.name
HAVING COUNT(e.id) > 0
ORDER BY total_amount DESC
`

type GetCategoryBreakdownBySiteRow struct {
	CategoryID   pgtype.UUID    `json:"category_id"`
	CategoryName string         `json:"category_name"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
	ExpenseCount int64          `json:"expense_count"`
}

func (q *Queries) GetCategoryBreakdownBySite(ctx context.Context, siteID pgtype.UUID) ([]GetCategoryBreakdownBySiteRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreakdownBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryBreakdownBySiteRow{}
	for rows.Next() {
		var i GetCategoryBreakdownBySiteRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.TotalAmount,
			&i.ExpenseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT
    e.id,
    e.site_id,
    e.category_id,
    c.name AS category_name,
    e.amount,
    e.description,
    e.expense_date,
    e.receipt_note,
    e.recorded_by,
    u.full_name AS recorded_by_name,
    e.created_at,
    e.updated_at
FROM expenses e
JOIN expense_categories c ON c.id = e.category_id
JOIN users u ON u.id = e.recorded_by
WHERE e.id = $1 AND e.site_id = $2
LIMIT 1
`

type GetExpenseByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

type GetExpenseByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	SiteID         pgtype.UUID        `json:"site_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	CategoryName   string             `json:"category_name"`
	Amount         pgtype.Numeric     `json:"amount"`
	Description    pgtype.Text        `json:"description"`
	ExpenseDate    pgtype.Date        `json:"expense_date"`
	ReceiptNote    pgtype.Text        `json:"receipt_note"`
	RecordedBy     pgtype.UUID        `json:"recorded_by"`
	RecordedByName string             `json:"recorded_by_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (GetExpenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, arg.ID, arg.SiteID)
	var i GetExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.CategoryID,
		&i.CategoryName,
		&i.Amount,
		&i.Description,
		&i.ExpenseDate,
		&i.ReceiptNote,
		&i.RecordedBy,
		&i.RecordedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseStatsBySite = `-- name: GetExpenseStatsBySite :one
SELECT
    COALESCE(SUM(amount), 0)::NUMERIC(10,2) AS total_amount,
    COALESCE(SUM(CASE WHEN expense_date >= DATE_TRUNC('month', CURRENT_DATE)::DATE THEN amount ELSE 0 END), 0)::NUMERIC(10,2) AS this_month_amount,
    COUNT(*)::BIGINT AS total_count
FROM expenses
WHERE site_id = $1
`

type GetExpenseStatsBySiteRow struct {
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	ThisMonthAmount pgtype.Numeric `json:"this_month_amount"`
	TotalCount      int64          `json:"total_count"`
}

func (q *Queries) GetExpenseStatsBySite(ctx context.Context, siteID pgtype.UUID) (GetExpenseStatsBySiteRow, error) {
	row := q.db.QueryRow(ctx, getExpenseStatsBySite, siteID)
	var i GetExpenseStatsBySiteRow
	err := row.Scan(&i.TotalAmount, &i.ThisMonthAmount, &i.TotalCount)
	return i, err
}

const listExpensesBySite = `-- name: ListExpensesBySite :many
SELECT
    e.id,
    e.site_id,
    e.category_id,
    c.name AS category_name,
    e.amount,
    e.description,
    e.expense_date,
    e.receipt_note,
    e.recorded_by,
    u.full_name AS recorded_by_name,
    e.created_at,
    e.updated_at
FROM expenses e
JOIN expense_categories c ON c.id = e.category_id
JOIN users u ON u.id = e.recorded_by
WHERE e.site_id = $1
  AND ($2::UUID IS NULL OR e.category_id = $2)
  AND ($3::DATE IS NULL OR e.expense_date >= $3)
  AND ($4::DATE IS NULL OR e.expense_date <= $4)
ORDER BY e.expense_date DESC, e.created_at DESC
`

type ListExpensesBySiteParams struct {
	SiteID     pgtype.UUID `json:"site_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

type ListExpensesBySiteRow struct {
	ID             pgtype.UUID        `json:"id"`
	SiteID         pgtype.UUID        `json:"site_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	CategoryName   string             `json:"category_name"`
	Amount         pgtype.Numeric     `json:"amount"`
	Description    pgtype.Text        `json:"description"`
	ExpenseDate    pgtype.Date        `json:"expense_date"`
	ReceiptNote    pgtype.Text        `json:"receipt_note"`
	RecordedBy     pgtype.UUID        `json:"recorded_by"`
	RecordedByName string             `json:"recorded_by_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListExpensesBySite(ctx context.Context, arg ListExpensesBySiteParams) ([]ListExpensesBySiteRow, error) {
	rows, err := q.db.Query(ctx, listExpensesBySite,
		arg.SiteID,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesBySiteRow{}
	for rows.Next() {
		var i ListExpensesBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.CategoryID,
			&i.CategoryName,
			&i.Amount,
			&i.Description,
			&i.ExpenseDate,
			&i.ReceiptNote,
			&i.RecordedBy,
			&i.RecordedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
