// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpensesByCategoryID = `-- name: CountExpensesByCategoryID :one
SELECT COUNT(*) FROM expenses
WHERE category_id = $1 AND site_id = $2
`

type CountExpensesByCategoryIDParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	SiteID     pgtype.UUID `json:"site_id"`
}

func (q *Queries) CountExpensesByCategoryID(ctx context.Context, arg CountExpensesByCategoryIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpensesByCategoryID, arg.CategoryID, arg.SiteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (site_id, name, is_default, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, site_id, name, is_default, is_active, created_at
`

type CreateExpenseCategoryParams struct {
	SiteID    pgtype.UUID `json:"site_id"`
	Name      string      `json:"name"`
	IsDefault bool        `json:"is_default"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategories, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory,
		arg.SiteID,
		arg.Name,
		arg.IsDefault,
		arg.IsActive,
	)
	var i ExpenseCategories
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpenseCategory = `-- name: DeleteExpenseCategory :exec
DELETE FROM expense_categories
WHERE id = $1 AND site_id = $2
`

type DeleteExpenseCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) DeleteExpenseCategory(ctx context.Context, arg DeleteExpenseCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteExpenseCategory, arg.ID, arg.SiteID)
	return err
}

const getExpenseCategoryByID = `-- name: GetExpenseCategoryByID :one
SELECT id, site_id, name, is_default, is_active, created_at FROM expense_categories
WHERE id = $1 AND site_id = $2
LIMIT 1
`

type GetExpenseCategoryByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) GetExpenseCategoryByID(ctx context.Context, arg GetExpenseCategoryByIDParams) (ExpenseCategories, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryByID, arg.ID, arg.SiteID)
	var i ExpenseCategories
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAllExpenseCategoriesBySiteID = `-- name: ListAllExpenseCategoriesBySiteID :many
SELECT id, site_id, name, is_default, is_active, created_at FROM expense_categories
WHERE site_id = $1
ORDER BY is_active DESC, name ASC
`

func (q *Queries) ListAllExpenseCategoriesBySiteID(ctx context.Context, siteID pgtype.UUID) ([]ExpenseCategories, error) {
	rows, err := q.db.Query(ctx, listAllExpenseCategoriesBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategories{}
	for rows.Next() {
		var i ExpenseCategories
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseCategoriesBySiteID = `-- name: ListExpenseCategoriesBySiteID :many
SELECT id, site_id, name, is_default, is_active, created_at FROM expense_categories
WHERE site_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListExpenseCategoriesBySiteID(ctx context.Context, siteID pgtype.UUID) ([]ExpenseCategories, error) {
	rows, err := q.db.Query(ctx, listExpenseCategoriesBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategories{}
	for rows.Next() {
		var i ExpenseCategories
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories
SET name = $3, is_active = $4
WHERE id = $1 AND site_id = $2
RETURNING id, site_id, name, is_default, is_active, created_at
`

type UpdateExpenseCategoryParams struct {
	ID       pgtype.UUID `json:"id"`
	SiteID   pgtype.UUID `json:"site_id"`
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategories, error) {
	row := q.db.QueryRow(ctx, updateExpenseCategory,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.IsActive,
	)
	var i ExpenseCategories
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
