// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meter_types.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPeriodsByMeterTypeID = `-- name: CountPeriodsByMeterTypeID :one
SELECT COUNT(*) FROM consumption_periods
WHERE meter_type_id = $1 AND site_id = $2
`

type CountPeriodsByMeterTypeIDParams struct {
	MeterTypeID pgtype.UUID `json:"meter_type_id"`
	SiteID      pgtype.UUID `json:"site_id"`
}

func (q *Queries) CountPeriodsByMeterTypeID(ctx context.Context, arg CountPeriodsByMeterTypeIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPeriodsByMeterTypeID, arg.MeterTypeID, arg.SiteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMeterType = `-- name: CreateMeterType :one
INSERT INTO meter_types (site_id, name, unit, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, site_id, name, unit, is_active, created_at
`

type CreateMeterTypeParams struct {
	SiteID   pgtype.UUID `json:"site_id"`
	Name     string      `json:"name"`
	Unit     string      `json:"unit"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) CreateMeterType(ctx context.Context, arg CreateMeterTypeParams) (MeterTypes, error) {
	row := q.db.QueryRow(ctx, createMeterType,
		arg.SiteID,
		arg.Name,
		arg.Unit,
		arg.IsActive,
	)
	var i MeterTypes
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMeterType = `-- name: DeleteMeterType :exec
DELETE FROM meter_types
WHERE id = $1 AND site_id = $2
`

type DeleteMeterTypeParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) DeleteMeterType(ctx context.Context, arg DeleteMeterTypeParams) error {
	_, err := q.db.Exec(ctx, deleteMeterType, arg.ID, arg.SiteID)
	return err
}

const getMeterTypeByID = `-- name: GetMeterTypeByID :one
SELECT id, site_id, name, unit, is_active, created_at FROM meter_types
WHERE id = $1 AND site_id = $2
LIMIT 1
`

type GetMeterTypeByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) GetMeterTypeByID(ctx context.Context, arg GetMeterTypeByIDParams) (MeterTypes, error) {
	row := q.db.QueryRow(ctx, getMeterTypeByID, arg.ID, arg.SiteID)
	var i MeterTypes
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAllMeterTypesBySiteID = `-- name: ListAllMeterTypesBySiteID :many
SELECT id, site_id, name, unit, is_active, created_at FROM meter_types
WHERE site_id = $1
ORDER BY is_active DESC, name ASC
`

func (q *Queries) ListAllMeterTypesBySiteID(ctx context.Context, siteID pgtype.UUID) ([]MeterTypes, error) {
	rows, err := q.db.Query(ctx, listAllMeterTypesBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeterTypes{}
	for rows.Next() {
		var i MeterTypes
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeterTypesBySiteID = `-- name: ListMeterTypesBySiteID :many
SELECT id, site_id, name, unit, is_active, created_at FROM meter_types
WHERE site_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListMeterTypesBySiteID(ctx context.Context, siteID pgtype.UUID) ([]MeterTypes, error) {
	rows, err := q.db.Query(ctx, listMeterTypesBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeterTypes{}
	for rows.Next() {
		var i MeterTypes
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeterType = `-- name: UpdateMeterType :one
UPDATE meter_types
SET name = $3, unit = $4, is_active = $5
WHERE id = $1 AND site_id = $2
RETURNING id, site_id, name, unit, is_active, created_at
`

type UpdateMeterTypeParams struct {
	ID       pgtype.UUID `json:"id"`
	SiteID   pgtype.UUID `json:"site_id"`
	Name     string      `json:"name"`
	Unit     string      `json:"unit"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateMeterType(ctx context.Context, arg UpdateMeterTypeParams) (MeterTypes, error) {
	row := q.db.QueryRow(ctx, updateMeterType,
		arg.ID,
		arg.SiteID,
		arg.Name,
		arg.Unit,
		arg.IsActive,
	)
	var i MeterTypes
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
