// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Announcements struct {
	ID          pgtype.UUID        `json:"id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Priority    string             `json:"priority"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Apartments struct {
	ID           pgtype.UUID        `json:"id"`
	SiteID       pgtype.UUID        `json:"site_id"`
	BlockID      pgtype.UUID        `json:"block_id"`
	DoorNumber   string             `json:"door_number"`
	Floor        pgtype.Int4        `json:"floor"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	TenantUserID pgtype.UUID        `json:"tenant_user_id"`
	IsActive     bool               `json:"is_active"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Blocks struct {
	ID        pgtype.UUID        `json:"id"`
	SiteID    pgtype.UUID        `json:"site_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ConsumptionPeriods struct {
	ID                         pgtype.UUID        `json:"id"`
	SiteID                     pgtype.UUID        `json:"site_id"`
	MeterTypeID                pgtype.UUID        `json:"meter_type_id"`
	Period                     pgtype.Date        `json:"period"`
	MainMeterPrevious          pgtype.Numeric     `json:"main_meter_previous"`
	MainMeterCurrent           pgtype.Numeric     `json:"main_meter_current"`
	TotalBilledConsumption     pgtype.Numeric     `json:"total_billed_consumption"`
	TotalApartmentsConsumption pgtype.Numeric     `json:"total_apartments_consumption"`
	CommonAreaConsumption      pgtype.Numeric     `json:"common_area_consumption"`
	TotalBillAmount            pgtype.Numeric     `json:"total_bill_amount"`
	UnitCost                   pgtype.Numeric     `json:"unit_cost"`
	CommonAreaCost             pgtype.Numeric     `json:"common_area_cost"`
	BillDate                   pgtype.Date        `json:"bill_date"`
	BillNo                     pgtype.Text        `json:"bill_no"`
	Description                pgtype.Text        `json:"description"`
	CreatedBy                  pgtype.UUID        `json:"created_by"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type DebtSummary struct {
	ID           pgtype.UUID        `json:"id"`
	SiteID       pgtype.UUID        `json:"site_id"`
	ApartmentID  pgtype.UUID        `json:"apartment_id"`
	DebtorUserID pgtype.UUID        `json:"debtor_user_id"`
	Type         string             `json:"type"`
	Amount       pgtype.Numeric     `json:"amount"`
	DueMonth     pgtype.Date        `json:"due_month"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PaidAmount   interface{}        `json:"paid_amount"`
	Remaining    interface{}        `json:"remaining"`
}

type Debts struct {
	ID           pgtype.UUID        `json:"id"`
	SiteID       pgtype.UUID        `json:"site_id"`
	ApartmentID  pgtype.UUID        `json:"apartment_id"`
	DebtorUserID pgtype.UUID        `json:"debtor_user_id"`
	Type         string             `json:"type"`
	Amount       pgtype.Numeric     `json:"amount"`
	DueMonth     pgtype.Date        `json:"due_month"`
	Description  pgtype.Text        `json:"description"`
	Status       string             `json:"status"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DueRates struct {
	ID        pgtype.UUID        `json:"id"`
	SiteID    pgtype.UUID        `json:"site_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	ValidFrom pgtype.Date        `json:"valid_from"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExpenseCategories struct {
	ID        pgtype.UUID        `json:"id"`
	SiteID    pgtype.UUID        `json:"site_id"`
	Name      string             `json:"name"`
	IsDefault bool               `json:"is_default"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Expenses struct {
	ID          pgtype.UUID        `json:"id"`
	SiteID      pgtype.UUID        `json:"site_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Description pgtype.Text        `json:"description"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	ReceiptNote pgtype.Text        `json:"receipt_note"`
	RecordedBy  pgtype.UUID        `json:"recorded_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MeterReadings struct {
	ID                  pgtype.UUID        `json:"id"`
	ConsumptionPeriodID pgtype.UUID        `json:"consumption_period_id"`
	ApartmentID         pgtype.UUID        `json:"apartment_id"`
	PreviousReading     pgtype.Numeric     `json:"previous_reading"`
	CurrentReading      pgtype.Numeric     `json:"current_reading"`
	Consumption         pgtype.Numeric     `json:"consumption"`
	IndividualAmount    pgtype.Numeric     `json:"individual_amount"`
	CommonAreaAmount    pgtype.Numeric     `json:"common_area_amount"`
	TotalAmount         pgtype.Numeric     `json:"total_amount"`
	DebtID              pgtype.UUID        `json:"debt_id"`
	DebtorUserID        pgtype.UUID        `json:"debtor_user_id"`
	ReadingDate         pgtype.Date        `json:"reading_date"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type MeterTypes struct {
	ID        pgtype.UUID        `json:"id"`
	SiteID    pgtype.UUID        `json:"site_id"`
	Name      string             `json:"name"`
	Unit      string             `json:"unit"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MonthlyCashflow struct {
	SiteID   pgtype.UUID     `json:"site_id"`
	Month    pgtype.Interval `json:"month"`
	FlowType string          `json:"flow_type"`
	Total    int64           `json:"total"`
}

type Payments struct {
	ID            pgtype.UUID        `json:"id"`
	DebtID        pgtype.UUID        `json:"debt_id"`
	SiteID        pgtype.UUID        `json:"site_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	PaymentDate   pgtype.Date        `json:"payment_date"`
	Notes         pgtype.Text        `json:"notes"`
	RecordedBy    pgtype.UUID        `json:"recorded_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RefreshTokens struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Sites struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Address        pgtype.Text        `json:"address"`
	ApartmentLimit int32              `json:"apartment_limit"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	InitialBalance pgtype.Numeric     `json:"initial_balance"`
}

type TenantHistory struct {
	ID           pgtype.UUID        `json:"id"`
	ApartmentID  pgtype.UUID        `json:"apartment_id"`
	TenantUserID pgtype.UUID        `json:"tenant_user_id"`
	StartedAt    pgtype.Date        `json:"started_at"`
	EndedAt      pgtype.Date        `json:"ended_at"`
	DebtAction   pgtype.Text        `json:"debt_action"`
	Notes        pgtype.Text        `json:"notes"`
	RecordedBy   pgtype.UUID        `json:"recorded_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Users struct {
	ID           pgtype.UUID        `json:"id"`
	SiteID       pgtype.UUID        `json:"site_id"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Phone        string             `json:"phone"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
