// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    debt_id, site_id, amount, payment_method, payment_date, notes, recorded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, debt_id, site_id, amount, payment_method, payment_date, notes, recorded_by, created_at
`

type CreatePaymentParams struct {
	DebtID        pgtype.UUID    `json:"debt_id"`
	SiteID        pgtype.UUID    `json:"site_id"`
	Amount        pgtype.Numeric `json:"amount"`
	PaymentMethod pgtype.Text    `json:"payment_method"`
	PaymentDate   pgtype.Date    `json:"payment_date"`
	Notes         pgtype.Text    `json:"notes"`
	RecordedBy    pgtype.UUID    `json:"recorded_by"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payments, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.DebtID,
		arg.SiteID,
		arg.Amount,
		arg.PaymentMethod,
		arg.PaymentDate,
		arg.Notes,
		arg.RecordedBy,
	)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.SiteID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentDate,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePaymentByID = `-- name: DeletePaymentByID :exec
DELETE FROM payments
WHERE id = $1 AND site_id = $2
`

type DeletePaymentByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

func (q *Queries) DeletePaymentByID(ctx context.Context, arg DeletePaymentByIDParams) error {
	_, err := q.db.Exec(ctx, deletePaymentByID, arg.ID, arg.SiteID)
	return err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT 
    p.id,
    p.debt_id,
    p.site_id,
    p.amount,
    p.payment_method,
    p.payment_date,
    p.notes,
    p.recorded_by,
    p.created_at,
    u.full_name AS recorded_by_name,
    d.type AS debt_type,
    d.due_month AS debt_due_month,
    d.description AS debt_description,
    d.amount AS debt_total_amount,
    a.door_number,
    COALESCE(b.name, '') AS block_name,
    debtor.full_name AS debtor_full_name,
    debtor.phone AS debtor_phone
FROM payments p
JOIN users u ON u.id = p.recorded_by
JOIN debts d ON d.id = p.debt_id
JOIN apartments a ON a.id = d.apartment_id
LEFT JOIN blocks b ON b.id = a.block_id
JOIN users debtor ON debtor.id = d.debtor_user_id
WHERE p.id = $1 AND p.site_id = $2
`

type GetPaymentByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	SiteID pgtype.UUID `json:"site_id"`
}

type GetPaymentByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	DebtID          pgtype.UUID        `json:"debt_id"`
	SiteID          pgtype.UUID        `json:"site_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	PaymentMethod   pgtype.Text        `json:"payment_method"`
	PaymentDate     pgtype.Date        `json:"payment_date"`
	Notes           pgtype.Text        `json:"notes"`
	RecordedBy      pgtype.UUID        `json:"recorded_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RecordedByName  string             `json:"recorded_by_name"`
	DebtType        string             `json:"debt_type"`
	DebtDueMonth    pgtype.Date        `json:"debt_due_month"`
	DebtDescription pgtype.Text        `json:"debt_description"`
	DebtTotalAmount pgtype.Numeric     `json:"debt_total_amount"`
	DoorNumber      string             `json:"door_number"`
	BlockName       string             `json:"block_name"`
	DebtorFullName  string             `json:"debtor_full_name"`
	DebtorPhone     string             `json:"debtor_phone"`
}

func (q *Queries) GetPaymentByID(ctx context.Context, arg GetPaymentByIDParams) (GetPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, arg.ID, arg.SiteID)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.SiteID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentDate,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.RecordedByName,
		&i.DebtType,
		&i.DebtDueMonth,
		&i.DebtDescription,
		&i.DebtTotalAmount,
		&i.DoorNumber,
		&i.BlockName,
		&i.DebtorFullName,
		&i.DebtorPhone,
	)
	return i, err
}

const getPaymentStatsBySite = `-- name: GetPaymentStatsBySite :one
SELECT 
    COALESCE(SUM(amount), 0)::NUMERIC(12,2) AS total_collected,
    COALESCE(SUM(CASE WHEN payment_method = 'cash' THEN amount ELSE 0 END), 0)::NUMERIC(12,2) AS cash_total,
    COALESCE(SUM(CASE WHEN payment_method = 'transfer' THEN amount ELSE 0 END), 0)::NUMERIC(12,2) AS transfer_total,
    COUNT(*)::INT AS total_count
FROM payments
WHERE site_id = $1
`

type GetPaymentStatsBySiteRow struct {
	TotalCollected pgtype.Numeric `json:"total_collected"`
	CashTotal      pgtype.Numeric `json:"cash_total"`
	TransferTotal  pgtype.Numeric `json:"transfer_total"`
	TotalCount     int32          `json:"total_count"`
}

func (q *Queries) GetPaymentStatsBySite(ctx context.Context, siteID pgtype.UUID) (GetPaymentStatsBySiteRow, error) {
	row := q.db.QueryRow(ctx, getPaymentStatsBySite, siteID)
	var i GetPaymentStatsBySiteRow
	err := row.Scan(
		&i.TotalCollected,
		&i.CashTotal,
		&i.TransferTotal,
		&i.TotalCount,
	)
	return i, err
}

const getTotalPaidForDebt = `-- name: GetTotalPaidForDebt :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(10,2) AS total_paid
FROM payments
WHERE debt_id = $1
`

func (q *Queries) GetTotalPaidForDebt(ctx context.Context, debtID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalPaidForDebt, debtID)
	var total_paid pgtype.Numeric
	err := row.Scan(&total_paid)
	return total_paid, err
}

const listPaymentsByDebt = `-- name: ListPaymentsByDebt :many
SELECT 
    p.id,
    p.debt_id,
    p.site_id,
    p.amount,
    p.payment_method,
    p.payment_date,
    p.notes,
    p.recorded_by,
    p.created_at,
    u.full_name AS recorded_by_name
FROM payments p
JOIN users u ON u.id = p.recorded_by
WHERE p.debt_id = $1 AND p.site_id = $2
ORDER BY p.payment_date DESC, p.created_at DESC
`

type ListPaymentsByDebtParams struct {
	DebtID pgtype.UUID `json:"debt_id"`
	SiteID pgtype.UUID `json:"site_id"`
}

type ListPaymentsByDebtRow struct {
	ID             pgtype.UUID        `json:"id"`
	DebtID         pgtype.UUID        `json:"debt_id"`
	SiteID         pgtype.UUID        `json:"site_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaymentMethod  pgtype.Text        `json:"payment_method"`
	PaymentDate    pgtype.Date        `json:"payment_date"`
	Notes          pgtype.Text        `json:"notes"`
	RecordedBy     pgtype.UUID        `json:"recorded_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RecordedByName string             `json:"recorded_by_name"`
}

func (q *Queries) ListPaymentsByDebt(ctx context.Context, arg ListPaymentsByDebtParams) ([]ListPaymentsByDebtRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsByDebt, arg.DebtID, arg.SiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsByDebtRow{}
	for rows.Next() {
		var i ListPaymentsByDebtRow
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.SiteID,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentDate,
			&i.Notes,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsBySite = `-- name: ListPaymentsBySite :many
SELECT 
    p.id,
    p.debt_id,
    p.site_id,
    p.amount,
    p.payment_method,
    p.payment_date,
    p.notes,
    p.recorded_by,
    p.created_at,
    u.full_name AS recorded_by_name,
    d.type AS debt_type,
    d.due_month AS debt_due_month,
    d.description AS debt_description,
    d.amount AS debt_total_amount,
    a.door_number,
    COALESCE(b.name, '') AS block_name,
    debtor.full_name AS debtor_full_name,
    debtor.phone AS debtor_phone
FROM payments p
JOIN users u ON u.id = p.recorded_by
JOIN debts d ON d.id = p.debt_id
JOIN apartments a ON a.id = d.apartment_id
LEFT JOIN blocks b ON b.id = a.block_id
JOIN users debtor ON debtor.id = d.debtor_user_id
WHERE p.site_id = $1
  AND ($2::UUID IS NULL OR p.debt_id = $2)
  AND ($3::UUID IS NULL OR d.apartment_id = $3)
  AND ($4::TEXT IS NULL OR p.payment_method = $4)
  AND ($5::DATE IS NULL OR p.payment_date >= $5)
  AND ($6::DATE IS NULL OR p.payment_date <= $6)
  AND ($7::UUID IS NULL OR d.debtor_user_id = $7)
ORDER BY p.payment_date DESC, p.created_at DESC
`

type ListPaymentsBySiteParams struct {
	SiteID        pgtype.UUID `json:"site_id"`
	DebtID        pgtype.UUID `json:"debt_id"`
	ApartmentID   pgtype.UUID `json:"apartment_id"`
	PaymentMethod pgtype.Text `json:"payment_method"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	DebtorUserID  pgtype.UUID `json:"debtor_user_id"`
}

type ListPaymentsBySiteRow struct {
	ID              pgtype.UUID        `json:"id"`
	DebtID          pgtype.UUID        `json:"debt_id"`
	SiteID          pgtype.UUID        `json:"site_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	PaymentMethod   pgtype.Text        `json:"payment_method"`
	PaymentDate     pgtype.Date        `json:"payment_date"`
	Notes           pgtype.Text        `json:"notes"`
	RecordedBy      pgtype.UUID        `json:"recorded_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	RecordedByName  string             `json:"recorded_by_name"`
	DebtType        string             `json:"debt_type"`
	DebtDueMonth    pgtype.Date        `json:"debt_due_month"`
	DebtDescription pgtype.Text        `json:"debt_description"`
	DebtTotalAmount pgtype.Numeric     `json:"debt_total_amount"`
	DoorNumber      string             `json:"door_number"`
	BlockName       string             `json:"block_name"`
	DebtorFullName  string             `json:"debtor_full_name"`
	DebtorPhone     string             `json:"debtor_phone"`
}

func (q *Queries) ListPaymentsBySite(ctx context.Context, arg ListPaymentsBySiteParams) ([]ListPaymentsBySiteRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsBySite,
		arg.SiteID,
		arg.DebtID,
		arg.ApartmentID,
		arg.PaymentMethod,
		arg.StartDate,
		arg.EndDate,
		arg.DebtorUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsBySiteRow{}
	for rows.Next() {
		var i ListPaymentsBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.SiteID,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentDate,
			&i.Notes,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.RecordedByName,
			&i.DebtType,
			&i.DebtDueMonth,
			&i.DebtDescription,
			&i.DebtTotalAmount,
			&i.DoorNumber,
			&i.BlockName,
			&i.DebtorFullName,
			&i.DebtorPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
