// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AccrueMonthlyDue(ctx context.Context, arg AccrueMonthlyDueParams) (pgtype.UUID, error)
	CountActiveApartmentsBySiteID(ctx context.Context, siteID pgtype.UUID) (int64, error)
	CountExpensesByCategoryID(ctx context.Context, arg CountExpensesByCategoryIDParams) (int64, error)
	CountPeriodsByMeterTypeID(ctx context.Context, arg CountPeriodsByMeterTypeIDParams) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcements, error)
	CreateApartment(ctx context.Context, arg CreateApartmentParams) (Apartments, error)
	CreateBlock(ctx context.Context, arg CreateBlockParams) (Blocks, error)
	CreateConsumptionPeriod(ctx context.Context, arg CreateConsumptionPeriodParams) (ConsumptionPeriods, error)
	CreateDebt(ctx context.Context, arg CreateDebtParams) (Debts, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expenses, error)
	CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategories, error)
	CreateMeterReading(ctx context.Context, arg CreateMeterReadingParams) (MeterReadings, error)
	CreateMeterType(ctx context.Context, arg CreateMeterTypeParams) (MeterTypes, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payments, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshTokens, error)
	CreateSite(ctx context.Context, arg CreateSiteParams) (Sites, error)
	CreateTenantHistory(ctx context.Context, arg CreateTenantHistoryParams) (TenantHistory, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteAnnouncement(ctx context.Context, arg DeleteAnnouncementParams) error
	DeleteBlock(ctx context.Context, arg DeleteBlockParams) error
	DeleteConsumptionPeriod(ctx context.Context, arg DeleteConsumptionPeriodParams) error
	DeleteDebtByID(ctx context.Context, arg DeleteDebtByIDParams) error
	DeleteExpenseByID(ctx context.Context, arg DeleteExpenseByIDParams) error
	DeleteExpenseCategory(ctx context.Context, arg DeleteExpenseCategoryParams) error
	DeleteMeterType(ctx context.Context, arg DeleteMeterTypeParams) error
	DeleteOpenDebtsByDebtor(ctx context.Context, arg DeleteOpenDebtsByDebtorParams) error
	DeletePaymentByID(ctx context.Context, arg DeletePaymentByIDParams) error
	EndTenantHistory(ctx context.Context, arg EndTenantHistoryParams) error
	GetAnnouncementByID(ctx context.Context, arg GetAnnouncementByIDParams) (GetAnnouncementByIDRow, error)
	GetApartmentByID(ctx context.Context, arg GetApartmentByIDParams) (GetApartmentByIDRow, error)
	GetCategoryBreakdownBySite(ctx context.Context, siteID pgtype.UUID) ([]GetCategoryBreakdownBySiteRow, error)
	GetConsumptionPeriodByID(ctx context.Context, arg GetConsumptionPeriodByIDParams) (GetConsumptionPeriodByIDRow, error)
	GetCurrentDueRate(ctx context.Context, arg GetCurrentDueRateParams) (DueRates, error)
	GetDebtDetailByID(ctx context.Context, arg GetDebtDetailByIDParams) (GetDebtDetailByIDRow, error)
	GetDebtIDsByPeriodID(ctx context.Context, consumptionPeriodID pgtype.UUID) ([]pgtype.UUID, error)
	GetDebtsStatsBySite(ctx context.Context, siteID pgtype.UUID) (GetDebtsStatsBySiteRow, error)
	GetDueRateHistory(ctx context.Context, siteID pgtype.UUID) ([]GetDueRateHistoryRow, error)
	GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (GetExpenseByIDRow, error)
	GetExpenseCategoryByID(ctx context.Context, arg GetExpenseCategoryByIDParams) (ExpenseCategories, error)
	GetExpenseStatsBySite(ctx context.Context, siteID pgtype.UUID) (GetExpenseStatsBySiteRow, error)
	GetLastApartmentReadings(ctx context.Context, arg GetLastApartmentReadingsParams) ([]GetLastApartmentReadingsRow, error)
	GetLastMainMeterReading(ctx context.Context, arg GetLastMainMeterReadingParams) (pgtype.Numeric, error)
	GetMeterTypeByID(ctx context.Context, arg GetMeterTypeByIDParams) (MeterTypes, error)
	GetMonthlyCashflowBySite(ctx context.Context, siteID pgtype.UUID) ([]GetMonthlyCashflowBySiteRow, error)
	GetPaymentByID(ctx context.Context, arg GetPaymentByIDParams) (GetPaymentByIDRow, error)
	GetPaymentStatsBySite(ctx context.Context, siteID pgtype.UUID) (GetPaymentStatsBySiteRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshTokens, error)
	GetResidentMeterHistoryByApartmentID(ctx context.Context, apartmentID pgtype.UUID) ([]GetResidentMeterHistoryByApartmentIDRow, error)
	GetSiteByID(ctx context.Context, id pgtype.UUID) (Sites, error)
	GetSiteDetails(ctx context.Context, id pgtype.UUID) (GetSiteDetailsRow, error)
	GetSiteInitialBalance(ctx context.Context, id pgtype.UUID) (pgtype.Numeric, error)
	GetThisMonthIncomeBySite(ctx context.Context, siteID pgtype.UUID) (pgtype.Numeric, error)
	GetTotalIncomeBySite(ctx context.Context, siteID pgtype.UUID) (pgtype.Numeric, error)
	GetTotalPaidForDebt(ctx context.Context, debtID pgtype.UUID) (pgtype.Numeric, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (Users, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (Users, error)
	GetUserByPhone(ctx context.Context, phone string) (Users, error)
	GetUserByPhoneOrEmail(ctx context.Context, phone string) (Users, error)
	ListActiveApartmentsForAccrual(ctx context.Context, siteID pgtype.UUID) ([]ListActiveApartmentsForAccrualRow, error)
	ListAdminsBySiteID(ctx context.Context, siteID pgtype.UUID) ([]ListAdminsBySiteIDRow, error)
	ListAllExpenseCategoriesBySiteID(ctx context.Context, siteID pgtype.UUID) ([]ExpenseCategories, error)
	ListAllMeterTypesBySiteID(ctx context.Context, siteID pgtype.UUID) ([]MeterTypes, error)
	ListAllSiteIDs(ctx context.Context) ([]ListAllSiteIDsRow, error)
	ListAnnouncementsBySite(ctx context.Context, siteID pgtype.UUID) ([]ListAnnouncementsBySiteRow, error)
	ListApartmentsBySiteID(ctx context.Context, siteID pgtype.UUID) ([]ListApartmentsBySiteIDRow, error)
	ListBlocksBySiteID(ctx context.Context, siteID pgtype.UUID) ([]Blocks, error)
	ListConsumptionPeriodsBySite(ctx context.Context, siteID pgtype.UUID) ([]ListConsumptionPeriodsBySiteRow, error)
	ListDebtsBySite(ctx context.Context, arg ListDebtsBySiteParams) ([]ListDebtsBySiteRow, error)
	ListExpenseCategoriesBySiteID(ctx context.Context, siteID pgtype.UUID) ([]ExpenseCategories, error)
	ListExpensesBySite(ctx context.Context, arg ListExpensesBySiteParams) ([]ListExpensesBySiteRow, error)
	ListMeterReadingsByPeriodID(ctx context.Context, consumptionPeriodID pgtype.UUID) ([]ListMeterReadingsByPeriodIDRow, error)
	ListMeterTypesBySiteID(ctx context.Context, siteID pgtype.UUID) ([]MeterTypes, error)
	ListPaymentsByDebt(ctx context.Context, arg ListPaymentsByDebtParams) ([]ListPaymentsByDebtRow, error)
	ListPaymentsBySite(ctx context.Context, arg ListPaymentsBySiteParams) ([]ListPaymentsBySiteRow, error)
	ListSites(ctx context.Context) ([]ListSitesRow, error)
	ListTenantHistoryByApartmentID(ctx context.Context, apartmentID pgtype.UUID) ([]ListTenantHistoryByApartmentIDRow, error)
	RemoveApartmentTenant(ctx context.Context, arg RemoveApartmentTenantParams) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) (RefreshTokens, error)
	RevokeUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	SetApartmentOwner(ctx context.Context, arg SetApartmentOwnerParams) error
	SetApartmentTenant(ctx context.Context, arg SetApartmentTenantParams) error
	SoftDeleteApartment(ctx context.Context, arg SoftDeleteApartmentParams) error
	TransferOpenDebtsToOwner(ctx context.Context, arg TransferOpenDebtsToOwnerParams) error
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcements, error)
	UpdateApartment(ctx context.Context, arg UpdateApartmentParams) (Apartments, error)
	UpdateDebtStatus(ctx context.Context, arg UpdateDebtStatusParams) error
	UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategories, error)
	UpdateMeterType(ctx context.Context, arg UpdateMeterTypeParams) (MeterTypes, error)
	UpdateSiteInitialBalance(ctx context.Context, arg UpdateSiteInitialBalanceParams) (pgtype.Numeric, error)
	UpdateSiteLimit(ctx context.Context, arg UpdateSiteLimitParams) (Sites, error)
	UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (Users, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (Users, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (Users, error)
	UpsertDueRate(ctx context.Context, arg UpsertDueRateParams) (DueRates, error)
}

var _ Querier = (*Queries)(nil)
