// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (name, address, apartment_limit)
VALUES ($1, $2, $3)
RETURNING id, name, address, apartment_limit, created_at, updated_at, initial_balance
`

type CreateSiteParams struct {
	Name           string      `json:"name"`
	Address        pgtype.Text `json:"address"`
	ApartmentLimit int32       `json:"apartment_limit"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Sites, error) {
	row := q.db.QueryRow(ctx, createSite, arg.Name, arg.Address, arg.ApartmentLimit)
	var i Sites
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ApartmentLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialBalance,
	)
	return i, err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, name, address, apartment_limit, created_at, updated_at, initial_balance FROM sites
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSiteByID(ctx context.Context, id pgtype.UUID) (Sites, error) {
	row := q.db.QueryRow(ctx, getSiteByID, id)
	var i Sites
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ApartmentLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialBalance,
	)
	return i, err
}

const getSiteDetails = `-- name: GetSiteDetails :one
SELECT 
    s.id,
    s.name,
    s.address,
    s.apartment_limit,
    s.created_at,
    s.updated_at,
    COUNT(DISTINCT a.id)::int AS apartment_count,
    COUNT(DISTINCT b.id)::int AS block_count,
    COUNT(DISTINCT u.id)::int AS resident_count
FROM sites s
LEFT JOIN apartments a ON a.site_id = s.id AND a.is_active = TRUE
LEFT JOIN blocks b ON b.site_id = s.id
LEFT JOIN users u ON u.site_id = s.id AND u.role = 'resident' AND u.is_active = TRUE
WHERE s.id = $1
GROUP BY s.id
`

type GetSiteDetailsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Address        pgtype.Text        `json:"address"`
	ApartmentLimit int32              `json:"apartment_limit"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ApartmentCount int32              `json:"apartment_count"`
	BlockCount     int32              `json:"block_count"`
	ResidentCount  int32              `json:"resident_count"`
}

func (q *Queries) GetSiteDetails(ctx context.Context, id pgtype.UUID) (GetSiteDetailsRow, error) {
	row := q.db.QueryRow(ctx, getSiteDetails, id)
	var i GetSiteDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ApartmentLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApartmentCount,
		&i.BlockCount,
		&i.ResidentCount,
	)
	return i, err
}

const listAllSiteIDs = `-- name: ListAllSiteIDs :many
SELECT id, name FROM sites ORDER BY name ASC
`

type ListAllSiteIDsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListAllSiteIDs(ctx context.Context) ([]ListAllSiteIDsRow, error) {
	rows, err := q.db.Query(ctx, listAllSiteIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSiteIDsRow{}
	for rows.Next() {
		var i ListAllSiteIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT 
    s.id,
    s.name,
    s.address,
    s.apartment_limit,
    s.created_at,
    s.updated_at,
    COUNT(DISTINCT a.id)::int AS apartment_count,
    COUNT(DISTINCT u.id)::int AS admin_count
FROM sites s
LEFT JOIN apartments a ON a.site_id = s.id AND a.is_active = TRUE
LEFT JOIN users u ON u.site_id = s.id AND u.role = 'admin' AND u.is_active = TRUE
GROUP BY s.id
ORDER BY s.created_at DESC
`

type ListSitesRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Address        pgtype.Text        `json:"address"`
	ApartmentLimit int32              `json:"apartment_limit"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ApartmentCount int32              `json:"apartment_count"`
	AdminCount     int32              `json:"admin_count"`
}

func (q *Queries) ListSites(ctx context.Context) ([]ListSitesRow, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitesRow{}
	for rows.Next() {
		var i ListSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.ApartmentLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApartmentCount,
			&i.AdminCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteLimit = `-- name: UpdateSiteLimit :one
UPDATE sites
SET apartment_limit = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, address, apartment_limit, created_at, updated_at, initial_balance
`

type UpdateSiteLimitParams struct {
	ID             pgtype.UUID `json:"id"`
	ApartmentLimit int32       `json:"apartment_limit"`
}

func (q *Queries) UpdateSiteLimit(ctx context.Context, arg UpdateSiteLimitParams) (Sites, error) {
	row := q.db.QueryRow(ctx, updateSiteLimit, arg.ID, arg.ApartmentLimit)
	var i Sites
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.ApartmentLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InitialBalance,
	)
	return i, err
}
