// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantHistory = `-- name: CreateTenantHistory :one
INSERT INTO tenant_history (
    apartment_id,
    tenant_user_id,
    started_at,
    recorded_by
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, apartment_id, tenant_user_id, started_at, ended_at, debt_action, notes, recorded_by, created_at
`

type CreateTenantHistoryParams struct {
	ApartmentID  pgtype.UUID `json:"apartment_id"`
	TenantUserID pgtype.UUID `json:"tenant_user_id"`
	StartedAt    pgtype.Date `json:"started_at"`
	RecordedBy   pgtype.UUID `json:"recorded_by"`
}

func (q *Queries) CreateTenantHistory(ctx context.Context, arg CreateTenantHistoryParams) (TenantHistory, error) {
	row := q.db.QueryRow(ctx, createTenantHistory,
		arg.ApartmentID,
		arg.TenantUserID,
		arg.StartedAt,
		arg.RecordedBy,
	)
	var i TenantHistory
	err := row.Scan(
		&i.ID,
		&i.ApartmentID,
		&i.TenantUserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DebtAction,
		&i.Notes,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const endTenantHistory = `-- name: EndTenantHistory :exec
UPDATE tenant_history
SET ended_at = $3, debt_action = $4, notes = $5
WHERE apartment_id = $1 AND tenant_user_id = $2 AND ended_at IS NULL
`

type EndTenantHistoryParams struct {
	ApartmentID  pgtype.UUID `json:"apartment_id"`
	TenantUserID pgtype.UUID `json:"tenant_user_id"`
	EndedAt      pgtype.Date `json:"ended_at"`
	DebtAction   pgtype.Text `json:"debt_action"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) EndTenantHistory(ctx context.Context, arg EndTenantHistoryParams) error {
	_, err := q.db.Exec(ctx, endTenantHistory,
		arg.ApartmentID,
		arg.TenantUserID,
		arg.EndedAt,
		arg.DebtAction,
		arg.Notes,
	)
	return err
}

const listTenantHistoryByApartmentID = `-- name: ListTenantHistoryByApartmentID :many
SELECT 
    th.id, th.apartment_id, th.tenant_user_id, th.started_at, th.ended_at, th.debt_action, th.notes, th.recorded_by, th.created_at,
    u.full_name AS tenant_full_name,
    u.email AS tenant_email,
    u.phone AS tenant_phone
FROM tenant_history th
JOIN users u ON u.id = th.tenant_user_id
WHERE th.apartment_id = $1
ORDER BY th.started_at DESC
`

type ListTenantHistoryByApartmentIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	ApartmentID    pgtype.UUID        `json:"apartment_id"`
	TenantUserID   pgtype.UUID        `json:"tenant_user_id"`
	StartedAt      pgtype.Date        `json:"started_at"`
	EndedAt        pgtype.Date        `json:"ended_at"`
	DebtAction     pgtype.Text        `json:"debt_action"`
	Notes          pgtype.Text        `json:"notes"`
	RecordedBy     pgtype.UUID        `json:"recorded_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TenantFullName string             `json:"tenant_full_name"`
	TenantEmail    pgtype.Text        `json:"tenant_email"`
	TenantPhone    string             `json:"tenant_phone"`
}

func (q *Queries) ListTenantHistoryByApartmentID(ctx context.Context, apartmentID pgtype.UUID) ([]ListTenantHistoryByApartmentIDRow, error) {
	rows, err := q.db.Query(ctx, listTenantHistoryByApartmentID, apartmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantHistoryByApartmentIDRow{}
	for rows.Next() {
		var i ListTenantHistoryByApartmentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ApartmentID,
			&i.TenantUserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.DebtAction,
			&i.Notes,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.TenantFullName,
			&i.TenantEmail,
			&i.TenantPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
