// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: treasury.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMonthlyCashflowBySite = `-- name: GetMonthlyCashflowBySite :many
SELECT
    TO_CHAR(month, 'YYYY-MM')::TEXT AS month_str,
    flow_type,
    SUM(total)::NUMERIC(10,2) AS total
FROM monthly_cashflow
WHERE site_id = $1
GROUP BY TO_CHAR(month, 'YYYY-MM'), flow_type
ORDER BY month_str DESC
`

type GetMonthlyCashflowBySiteRow struct {
	MonthStr string         `json:"month_str"`
	FlowType string         `json:"flow_type"`
	Total    pgtype.Numeric `json:"total"`
}

func (q *Queries) GetMonthlyCashflowBySite(ctx context.Context, siteID pgtype.UUID) ([]GetMonthlyCashflowBySiteRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyCashflowBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyCashflowBySiteRow{}
	for rows.Next() {
		var i GetMonthlyCashflowBySiteRow
		if err := rows.Scan(&i.MonthStr, &i.FlowType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSiteInitialBalance = `-- name: GetSiteInitialBalance :one
SELECT initial_balance
FROM sites
WHERE id = $1
`

func (q *Queries) GetSiteInitialBalance(ctx context.Context, id pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getSiteInitialBalance, id)
	var initial_balance pgtype.Numeric
	err := row.Scan(&initial_balance)
	return initial_balance, err
}

const getThisMonthIncomeBySite = `-- name: GetThisMonthIncomeBySite :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(10,2) AS this_month_income
FROM payments
WHERE site_id = $1 AND payment_date >= DATE_TRUNC('month', CURRENT_DATE)::DATE
`

func (q *Queries) GetThisMonthIncomeBySite(ctx context.Context, siteID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getThisMonthIncomeBySite, siteID)
	var this_month_income pgtype.Numeric
	err := row.Scan(&this_month_income)
	return this_month_income, err
}

const getTotalIncomeBySite = `-- name: GetTotalIncomeBySite :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(10,2) AS total_income
FROM payments
WHERE site_id = $1
`

func (q *Queries) GetTotalIncomeBySite(ctx context.Context, siteID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalIncomeBySite, siteID)
	var total_income pgtype.Numeric
	err := row.Scan(&total_income)
	return total_income, err
}

const updateSiteInitialBalance = `-- name: UpdateSiteInitialBalance :one
UPDATE sites
SET initial_balance = $2, updated_at = NOW()
WHERE id = $1
RETURNING initial_balance
`

type UpdateSiteInitialBalanceParams struct {
	ID             pgtype.UUID    `json:"id"`
	InitialBalance pgtype.Numeric `json:"initial_balance"`
}

func (q *Queries) UpdateSiteInitialBalance(ctx context.Context, arg UpdateSiteInitialBalanceParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, updateSiteInitialBalance, arg.ID, arg.InitialBalance)
	var initial_balance pgtype.Numeric
	err := row.Scan(&initial_balance)
	return initial_balance, err
}
