// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users
WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    site_id,
    phone,
    email,
    password_hash,
    full_name,
    role,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, site_id, email, password_hash, full_name, phone, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	SiteID       pgtype.UUID `json:"site_id"`
	Phone        string      `json:"phone"`
	Email        pgtype.Text `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Role         string      `json:"role"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.SiteID,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.IsActive,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, site_id, email, password_hash, full_name, phone, role, is_active, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, site_id, email, password_hash, full_name, phone, role, is_active, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, site_id, email, password_hash, full_name, phone, role, is_active, created_at, updated_at FROM users
WHERE phone = $1
LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhoneOrEmail = `-- name: GetUserByPhoneOrEmail :one
SELECT id, site_id, email, password_hash, full_name, phone, role, is_active, created_at, updated_at FROM users
WHERE phone = $1 OR (email = $1 AND email IS NOT NULL)
LIMIT 1
`

func (q *Queries) GetUserByPhoneOrEmail(ctx context.Context, phone string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneOrEmail, phone)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminsBySiteID = `-- name: ListAdminsBySiteID :many
SELECT id, site_id, email, full_name, phone, role, is_active, created_at, updated_at
FROM users
WHERE site_id = $1 AND role = 'admin'
ORDER BY created_at DESC
`

type ListAdminsBySiteIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	SiteID    pgtype.UUID        `json:"site_id"`
	Email     pgtype.Text        `json:"email"`
	FullName  string             `json:"full_name"`
	Phone     string             `json:"phone"`
	Role      string             `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAdminsBySiteID(ctx context.Context, siteID pgtype.UUID) ([]ListAdminsBySiteIDRow, error) {
	rows, err := q.db.Query(ctx, listAdminsBySiteID, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminsBySiteIDRow{}
	for rows.Next() {
		var i ListAdminsBySiteIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Email,
			&i.FullName,
			&i.Phone,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, site_id, email, password_hash, full_name, phone, role, is_active, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (Users, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.IsActive)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
